name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Image Tag
        run: echo "IMAGE_TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        run: |
          docker build -t pappukrs/my-nodejs-app:${{ env.IMAGE_TAG }} -t pappukrs/my-nodejs-app:latest .
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push pappukrs/my-nodejs-app:${{ env.IMAGE_TAG }}
          docker push pappukrs/my-nodejs-app:latest

      - name: Update Deployment YAML with New Image Tag
        run: |
          sed -i "s|image: pappukrs/my-nodejs-app:.*|image: pappukrs/my-nodejs-app:${{ env.IMAGE_TAG }}|g" k8s/deployment.yaml

      - name: Commit and Push Updated Deployment YAML
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add k8s/deployment.yaml
          git commit -m "Update image tag to ${{ env.IMAGE_TAG }}"
          git push
